import School from "../components/ForSchoolPage/School";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Для школ | Профиград',
  description: 'Generated by create next app',
}

const ForSchool = () => {
  return (
    <div>
      <School/>
    </div>
  )
};

export default ForSchool;
