import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Отзывы | Профиград',
  description: 'Generated by create next app',
}

const Rewiews = () => {
  return (
    <div>
      
    </div>
  )
};

export default Rewiews;


