import { Metadata } from "next";

import RewiewsComponent from "../components/RewiewsPage/RewiewsComponent/RewiewsComponent";

export const metadata: Metadata = {
  title: 'Отзывы | Профиград',
  description: 'Generated by create next app',
}

const Rewiews = () => {
  return (
    <div>
      <RewiewsComponent/>
    </div>
  )
};

export default Rewiews;


