import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Экскурсии | Профиград',
  description: 'Generated by create next app',
}


const Contacts = () => {
  return (
    <div>
    </div>
  )
};

export default Contacts;
