import type { Metadata } from 'next'
import { Bebas_Neue } from 'next/font/google'
import './globals.css'

import { Providers } from './providers'

import Header from './components/mainpage/header/header'
import Footer from './components/mainpage/Footer/Footer'

import StyledComponentsRegistry from '../../lib/registry'

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Профиград - экскурсии',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <StyledComponentsRegistry>
          <body className={bebas.className}>
            <Header/>
              <Providers>{children}</Providers>
            <Footer/>
            </body>
        </StyledComponentsRegistry>
    </html>
  )
}
