import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Новости | Профиград',
  description: 'Generated by create next app',
}

const News = () => {
  return (
    <div>
    </div>
  )
};

export default News;
