import { Metadata } from "next";

import NewsComponent from "../components/NewsPage/NewsComponent/NewsComponent";

export const metadata: Metadata = {
  title: 'Новости | Профиград',
  description: 'Generated by create next app',
}

const News = () => {
  return (
    <>
      <NewsComponent/>
    </>
  )
};

export default News;
